### ISSUE TITLE
[page] wrong commit links on release notes

### ISSUE THREAD

**Issue by kares** [MariaDB/mariadb-connector-j#19]
https://mariadb.com/kb/en/mariadb/mariadb-connector-j-119-changelog/

the commits seem to be right but they're relative the server repo instead of this one 

e.g. **`https://github.com/MariaDB/server/commit/fae71ea`** does not exists 
but **`https://github.com/MariaDB/mariadb-connector-j/commit/fae71ea`** does

**Comment by rusher** [comment]
ok, thanks for reporting that, it will be corrected

**Comment by kares** [comment]
working like a charm now, thanks for the quick fix
