### ISSUE TITLE
[page] .tar.gz 1.1.9 release download not working

### ISSUE THREAD

**Issue by kares** [MariaDB/mariadb-connector-j#20]
tried a few mirrors ... https://downloads.mariadb.org/connector-java/1.1.9/#mirror=klaus

but the `.tar.gz` for **1.1.9** is not there (just its signature) ... did it get yanked or something?

here's the list of files on the mirror: http://mirror.klaus-uwe.me/mariadb/connector-java-1.1.9/

**Comment by rusher** [comment]
yes, there is a problem in delivery that is being resolved. 
It will be ok soon.

**Comment by dbart** [comment]
I've fixed the problem on the primary mirror. The tar.gz file should start going out to the other mirrors immediately (based on when the mirror next updates itself).

For now, go to the primary mirror for the file: http://ftp.osuosl.org/pub/mariadb/connector-java-1.1.9/

**Comment by kares** [comment]
OK, thank you both ... closing as resolved
